### PR TITLE
docs: remove my contribution details

### PR DESCRIPTION
**Pull request by cfanoulis**
This wrapper has gone way too off my ideas for it. Therefore, I will no longer contribute to it.

With this PR I have removed all my contribution details. **I am not giving up my copyrights, so my name shall persist in the licence. If it is removed, I will DMCA**

### CODE REVIEW

**Comment by Rexogamer** [comment]
What do you mean lmao? “It’s run by pizza” is your only excuse. You’re just salty she replaced your code... lol

**Comment by cfanoulis** [comment]
@Rexogamer I think I have provided enough context as to why I am leaving. No, I will not be deleting this PR

**Comment by Mitchell3514** [comment]
If you really wanted to leave so badly without getting attention... just commit directly and then leave the repo.

**Comment by cfanoulis** [comment]
I wanted to get a review from pizza, but alas.

**Comment by Rexogamer** [comment]
I’m sorry, but 

- how would the wrapper “leave your ideas” in any way other than your code getting yeeted?

- what do you expect pizza to say? “prettier borked”?

**Comment by cfanoulis** [comment]
@rexogamer if you want to discuss his, please feel free to contact me privately on Discord. GitHub isn't the place to discuss this

**Comment by Rexogamer** [comment]
sure

**Pull request merged**
